import {StyleSheet} from "react-native";
import {theme} from "../../global/styles/theme";

export const styles = StyleSheet.create({
    container:{
        flexDirection:"row",
        alignItems:"center"
    },
    user:{
        flexDirection:"row"
    },
    gretting:{
        fontFamily:theme.fonts.title500,
        fontSize:24,
        color:theme.colors.reading,
        marginRight:6
    },
    username:{
        fontFamily:theme.fonts.title700,
        fontSize:24,
        color:theme.colors.reading,
    },
    message:{
        fontFamily:theme.fonts.text400,
        color:theme.colors.highlight
    },
    textModalContainer:{
        marginTop:30,
        marginBottom:27,
        flexDirection:"row",
        justifyContent:"center"
    },
    defaultFontSize:{
        fontSize:24,
    },
    initialMessage:{
        fontFamily:theme.fonts.title500,
        color:theme.colors.reading,
    },
    whiteMessage:{
        fontFamily:theme.fonts.title700,
        color:theme.colors.reading
    },
    redMessage:{
        fontFamily:theme.fonts.title700,
        color:theme.colors.primary
    },
    buttonsModalContainer:{
        flexDirection:"row",
        justifyContent:"center",
    },
    backgroundCancelButton:{
        height:56,
        width:160,
        backgroundColor:theme.colors.secondary30,
        justifyContent:"center",
        alignItems:"center",
        marginRight:8,
        borderRadius:8
    },
    cancelButton:{
        height:54,
        width:158,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:theme.colors.secondary80,
        borderRadius:8,
    },
    backgroundConfirmButton:{
        height:56,
        width:160,
        backgroundColor:theme.colors.primary,
        justifyContent:"center",
        alignItems:"center",
        borderRadius:8
    },
    confirmButton:{
        height:54,
        width:158,
        backgroundColor:theme.colors.primary,
        justifyContent:"center",
        alignItems:"center",
        borderRadius:8
    },
    buttonText:{
        fontFamily:theme.fonts.text500,
        fontSize:15,
        color:theme.colors.reading
    }
});